##################################
#### ------------------------ ####
####  HEXTRUST - HADOLINT     ####
####  v1.0.0                  ####
#### ------------------------ ####
##################################
failure-threshold: error
override:
  info:
    - DL3018 # Not pinning package versions at this time
    - DL4006 # SHELL option ignored